version: "3"

services:
  airflow:
    image: apache/airflow:2.7.0

    container_name: airflow

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      PYTHONPATH: "/opt/airflow/dags"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

    command: airflow standalone